<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Task extends Model
{
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}
